edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"

# Stable options
reorder_imports = true
reorder_modules = true
use_small_heuristics = "Default"
match_block_trailing_comma = true
